using System;

namespace Apolon.Core.Attributes
{
    [AttributeUsage(AttributeTargets.Property)]
    public class ColumnAttribute : Attribute
    {
        public string Name { get; }
        public bool IsPrimaryKey { get; set; } = false;
        public bool IsNullable { get; set; } = true;
        public bool IsAutoGenerated { get; set; } = false;
        public bool Unique { get; set; } = false;
        public string? DefaultValue { get; set; } = null;
        public ColumnAttribute(string name)
        {
            Name = name;
        }
    }
}
