using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Apolon.Core.Attributes;
{
    
}

namespace Apolon.Core.ORM
{
    public static class ModelParser
    {
        private static readonly Dictionary<Type, ModelMetadata> _cache = new();

        public static ModelMetadata GetMetadata<T>()
        {
            var type = typeof(T);

            if (_cache.ContainsKey(type))
            {
                return _cache[type];
            }

            var tableAttr = type.GetCustomAttribute<TableAttribute>();
            if (tableAttr == null)
            {
                throw new InvalidOperationException(
                    $"Class {type.Name} is missing the [Table] attribute."
                );
            }

            var metadata = new ModelMetadata
            {
                TableName = tableAttr.Name
            };

            foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
            {
                var propMeta = ProcessProperty(prop);

                if (propMeta != null)
                {
                    metadata.Properties.Add(propMeta); 
                }
            }

            _cache[type] = metadata;
            return metadata;
        }

        private static PropertyMetadata? ProcessProperty(PropertyInfo prop)
        {
            var colAttr = prop.GetCustomAttribute<ColumnAttribute>();

            if (colAttr == null) return null;

            return new PropertyMetadata
            {
                PropertyName = prop.Name,
                ColumnName = colAttr.Name,
                PropertyType = prop.PropertyType,

                PostgresType = SqlTypeMapper.GetPostgresType(prop.PropertyType),

                IsPrimaryKey = colAttr.IsPrimaryKey,
                IsAutoGenerated = colAttr.IsAutoGenerated,
                IsNullable = colAttr.IsNullable,
                Unique = colAttr.Unique,
                DefaultValue = colAttr.DefaultValue,

                IsForeignKey = prop.Name.EndsWith("Id") && !colAttr.IsPrimaryKey
            };
        }
    }
}
