
using System.Text;

namespace Apolon.Core.ORM
{
    public static class PostgresDdlGenerator
    {
        public static string GenerateCreateTableSql(ModelMetadata metadata)
        {
            var sb = new StringBuilder();
            var tableName = metadata.TableName;
            var columnDefinitions = new List<string>();
            var primaryKeys = new List<string>();
            var uniqueConstraints = new List<string>();

            sb.AppendLine($"CREATE TABLE IF NOT EXISTS {tableName} (");

            foreach (var prop in metadata.Properties)
            {
                string columnSql = GenerateColumnDefinition(prop, primaryKeys, uniqueConstraints);

                columnDefinitions.Add(columnSql);
            }

            sb.Append(string.Join(",\n", columnDefinitions));

            sb.Append(GenerateTableConstraints(metadata.TableName, primaryKeys, uniqueConstraints));

            sb.AppendLine("\n);");

            return sb.ToString();
        }

        private static string GenerateColumnDefinition(PropertyMetadata prop,
                                                     List<string> primaryKeys,
                                                     List<string> uniqueConstraints)
        {
            var columnSql = new StringBuilder();
            columnSql.Append($"    {prop.ColumnName} ");

            if (prop.IsPrimaryKey && prop.IsAutoGenerated)
                columnSql.Append("SERIAL");
            else
                columnSql.Append(prop.PostgresType);

            if (!prop.IsNullable)
                columnSql.Append(" NOT NULL");

            if (!string.IsNullOrEmpty(prop.DefaultValue))
                columnSql.Append($" DEFAULT {prop.DefaultValue}");

            if (prop.Unique)
                uniqueConstraints.Add(prop.ColumnName);

            if (prop.IsPrimaryKey)
                primaryKeys.Add(prop.ColumnName);

            return columnSql.ToString();
        }

        private static string GenerateTableConstraints(string tableName,
                                                     List<string> primaryKeys,
                                                     List<string> uniqueConstraints)
        {
            var sb = new StringBuilder();

            if (primaryKeys.Any())
            {
                sb.AppendLine(
                    $",\n    CONSTRAINT pk_{tableName} PRIMARY KEY ({string.Join(", ", primaryKeys)})"
                );
            }

            if (uniqueConstraints.Any())
            {
                foreach (var colName in uniqueConstraints)
                {
                    sb.AppendLine($",\n    CONSTRAINT uq_{tableName}_{colName} UNIQUE ({colName})");
                }
            }

            return sb.ToString();
        }

        public static string GenerateForeignKeySql(ModelMetadata metadata)
        {
            var sb = new StringBuilder();
            var tableName = metadata.TableName;

            var foreignKeys = metadata.Properties.Where(p => p.IsForeignKey).ToList();

            foreach (var fk in foreignKeys)
            {
                var referencedTableName = fk.ColumnName.Replace("_id", "s");
                var referencedColumnName = fk.ColumnName;

                sb.AppendLine($"ALTER TABLE {tableName}");
                sb.AppendLine($"ADD CONSTRAINT fk_{tableName}_{fk.ColumnName} FOREIGN KEY ({fk.ColumnName})");
                sb.AppendLine($"REFERENCES {referencedTableName}({referencedColumnName});");
            }

            return sb.ToString();
        }
    }
}
