namespace Apolon.Core.ORM.Configuration
{
    public class ModelMetadata
    {
        public string TableName { get; set; } = string.Empty;
        public List<PropertyMetadata> Properties { get; set; } = new();
    }

    public class PropertyMetadata
    {
        public string PropertyName { get; set; } = string.Empty;
        public string ColumnName { get; set; } = string.Empty;
        public Type PropertyType { get; set; } = typeof(object);
        public string PostgresType { get; set; } = string.Empty;

        public bool IsPrimaryKey { get; set; }
        public bool IsAutoGenerated { get; set; }
        public bool IsNullable { get; set; }
        public bool IsForeignKey { get; set; }
        public bool Unique { get; set; }
        public string? DefaultValue { get; set; }
    }
}
