using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Apolon.Core.Attributes;

namespace Apolon.Core.Models
{
    [Table("checkups")]
    public class Checkup
    {
        [Column("checkup_id", IsPrimaryKey = true, IsAutoGenerated = true, IsNullable = false)]
        public int Id { get; set; }

        [Column("checkup_date", IsNullable = false)]
        public DateTime Date { get; set; }

        [Column("type", IsNullable = false)]
        public string CheckupType { get; set; } = string.Empty;

        [Column("finding")]
        public string? Finding { get; set; }

        [Column("patient_id", IsNullable = false)]
        public int PatientId { get; set; }

        public Patient? Patient { get; set; }
    }
}
