using Apolon.Core.ORM.Configuration.Attributes;
using Apolon.Core.Models.Enums;

namespace Apolon.Core.Models
{
    [Table("checkups")]
    public class Checkup
    {
        [Column("checkup_id", IsPrimaryKey = true, IsAutoGenerated = true, IsNullable = false)]
        public int Id { get; set; }

        [Column("checkup_date", IsNullable = false)]
        public DateTime Date { get; set; }

        [Column("type", IsNullable = false)]
        public CheckupType CheckupType { get; set; }

        [Column("finding")]
        public string? Finding { get; set; }

        [Column("patient_id", IsNullable = false)]
        public int PatientId { get; set; }

        public Patient? Patient { get; set; }
    }
}
