
using Apolon.Core.ORM.Configuration.Attributes;

namespace Apolon.Core.Models
{
    [Table("medications")]
    public class Medication
    {
        [Column("medication_id", IsPrimaryKey = true, IsAutoGenerated = true, IsNullable = false)]
        public int Id { get; set; }

        [Column("medication_name", IsNullable = false, Unique = true)]
        public string Name { get; set; } = string.Empty;

        [Column("manufacturer")]
        public string? Manufacturer { get; set; }
    }
}
