using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Apolon.Core.Attributes;

namespace Apolon.Core.Models
{
    [Table("medications")]
    public class Medication
    {
        [Column("medication_id", IsPrimaryKey = true, IsAutoGenerated = true, IsNullable = false)]
        public int Id { get; set; }

        [Column("medication_name", IsNullable = false, Unique = true)]
        public string Name { get; set; } = string.Empty;

        [Column("manufacturer")]
        public string? Manufacturer { get; set; }
    }
}
