using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Apolon.Core.Attributes;

namespace Apolon.Core.Models
{
    [Table("patients")]
    public class Patient
    {
        [Column("patient_id", IsPrimaryKey = true, IsAutoGenerated = true, IsNullable = false)]
        public int Id { get; set; }

        [Column("first_name", IsNullable = false)]
        public string FirstName { get; set; }

        [Column("last_name", IsNullable = false)]
        public string LastName { get; set; }

        [Column("oib")]
        public string OIB { get; set; }

        [Column("date_of_birth", IsNullable = false)]
        public DateTime DateOfBirth { get; set; }

        public List<Checkup>? Checkups { get; set; }
    }
}
