
using Apolon.Core.ORM.Configuration.Attributes;

namespace Apolon.Core.Models
{
    [Table("prescriptions")]
    public class Prescription
    {
        [Column("prescription_id", IsPrimaryKey = true, IsAutoGenerated = true, IsNullable = false)]
        public int Id { get; set; }

        [Column("patient_id", IsNullable = false)]
        public int PatientId { get; set; }

        [Column("medication_id", IsNullable = false)]
        public int MedicationId { get; set; }

        [Column("dosage", IsNullable = false)]
        public string Dosage { get; set; } = string.Empty;

        [Column("start_date", IsNullable = false)]
        public DateTime StartDate { get; set; }

        [Column("end_date")]
        public DateTime? EndDate { get; set; }

        public Patient? Patient { get; set; }
        public Medication? Medication { get; set; }
    }
}
