using Apolon.Core.ORM.Configuration.Attributes;

namespace Apolon.Core.Models
{
    [Table("__schema_version")]
    public class SchemaVersion
    {
        [Column("id", IsPrimaryKey = true, IsAutoGenerated = true, IsNullable = false)]
        public int Id { get; set; }

        [Column("version", IsNullable = false)]
        public string Version { get; set; } = string.Empty;

        [Column("applied_on", IsNullable = false)]
        public DateTime AppliedOn { get; set; }
    }
}
