using Npgsql;
using System.Data;

namespace Apolon.Core.ORM.Data
{
    public class GenericRepository<T> : IGenericRepository<T> where T : new()
    {
        private readonly DatabaseService _dbService;
        private readonly ModelMetadata _metadata;
        private readonly PropertyMetadata _pk;

        public GenericRepository(DatabaseService dbService)
        {
            _dbService = dbService;
            _metadata = ModelParser.GetMetadata<T>();

            _pk = _metadata.Properties.FirstOrDefault(p => p.IsPrimaryKey)
                ?? throw new InvalidOperationException(
                    $"Model {_metadata.TableName} has no primary key defined.");
        }

        private T MapEntityFromReader(NpgsqlDataReader reader)
        {
            var entity = new T();

            foreach (var propMeta in _metadata.Properties)
            {
                var propInfo = typeof(T).GetProperty(propMeta.PropertyName)!;

                int ordinal;
                try
                {
                    ordinal = reader.GetOrdinal(propMeta.ColumnName);
                }
                catch (IndexOutOfRangeException)
                {
                    continue;
                }

                if (!reader.IsDBNull(ordinal))
                {
                    var value = reader.GetValue(ordinal);

                    var targetType = Nullable.GetUnderlyingType(propInfo.PropertyType) ?? propInfo.PropertyType;

                    var convertedValue = Convert.ChangeType(value, targetType);

                    propInfo.SetValue(entity, convertedValue);
                }
            }
            return entity;
        }

        public async Task AddAsync(T entity)
        {
            var insertableProps = _metadata.Properties.Where(p => !p.IsAutoGenerated).ToList();

            if (!insertableProps.Any())
            {
                throw new InvalidOperationException($"Cannot insert into {_metadata.TableName}: No insertable columns found.");
            }

            var columns = string.Join(", ", insertableProps.Select(p => p.ColumnName));
            var parameters = string.Join(", ", insertableProps.Select(p => $"@{p.PropertyName}"));

            var sql = $"INSERT INTO {_metadata.TableName} ({columns}) VALUES ({parameters}) RETURNING {_pk.ColumnName}";

            await using var connection = await _dbService.GetNewOpenConnectionAsync();
            await using var command = new NpgsqlCommand(sql, connection);

            foreach (var propMeta in insertableProps)
            {
                var propInfo = typeof(T).GetProperty(propMeta.PropertyName)!;
                var value = propInfo.GetValue(entity);

                command.Parameters.AddWithValue($"@{propMeta.PropertyName}", value ?? DBNull.Value);
            }

            var newId = await command.ExecuteScalarAsync();

            if (newId != null)
            {
                var pkPropInfo = typeof(T).GetProperty(_pk.PropertyName)!;
                var convertedId = Convert.ChangeType(newId, pkPropInfo.PropertyType);
                pkPropInfo.SetValue(entity, convertedId);
            }
        }

        public async Task Update(T entity)
        {
            var updatableProps = _metadata.Properties
                .Where(p => !p.IsPrimaryKey)
                .ToList();
            if (!updatableProps.Any())
            {
                throw new InvalidOperationException($"Cannot update {_metadata.TableName}: No updatable columns found.");
            }
            var setClauses = string.Join(", ",
                updatableProps.Select(p => $"{p.ColumnName} = @{p.PropertyName}"));

            var sql = $"UPDATE {_metadata.TableName} SET {setClauses} WHERE {_pk.ColumnName} = @{_pk.PropertyName}";
            
            await using var connection = await _dbService.GetNewOpenConnectionAsync();
            await using var command = new NpgsqlCommand(sql, connection);

            foreach (var propMeta in updatableProps)
            {
                var propInfo = typeof(T).GetProperty(propMeta.PropertyName)!;
                var value = propInfo.GetValue(entity);

                command.Parameters.AddWithValue($"@{propMeta.PropertyName}", value ?? DBNull.Value);
            }

            var pkPropInfo = typeof(T).GetProperty(_pk.PropertyName)!;
            var pkValue = pkPropInfo.GetValue(entity);

            command.Parameters.AddWithValue(
                $"{_pk.PropertyName}", 
                pkValue ?? throw new InvalidOperationException("Cannot update entity with a null primary key."));
            
            await command.ExecuteNonQueryAsync();
        }

        public async Task DeleteAsync(object id)
        {
            var sql = $"DELETE FROM {_metadata.TableName} WHERE {_pk.ColumnName} = @id";

            await using var connection = await _dbService.GetNewOpenConnectionAsync();
            await using var command = new NpgsqlCommand(sql, connection);

            command.Parameters.AddWithValue("id", id);

            await command.ExecuteNonQueryAsync();
        }

        public async Task<IEnumerable<T>> GetAllAsync()
        {
            var results = new List<T>();

            var columnList = string.Join(", ", _metadata.Properties.Select(p => p.ColumnName));
            var sql = $"SELECT {columnList} FROM {_metadata.TableName}";

            await using var connection = await _dbService.GetNewOpenConnectionAsync();
            await using var command = new NpgsqlCommand(sql, connection);

            await using var reader = await command.ExecuteReaderAsync();

            while (await reader.ReadAsync())
            {
                results.Add(MapEntityFromReader(reader));
            }

            return results;
        }

        public async Task<T?> GetByIdAsync(object id)
        {
            var columnList = string.Join(", ", _metadata.Properties.Select(p => p.ColumnName));
            var sql = $"SELECT {columnList} FROM {_metadata.TableName} WHERE {_pk.ColumnName} = @id LIMIT 1";

            await using var connection = await _dbService.GetNewOpenConnectionAsync();
            await using var command = new NpgsqlCommand(sql, connection);

            command.Parameters.AddWithValue("id", id);

            await using var reader = await command.ExecuteReaderAsync();

            if (await reader.ReadAsync())
            {
                return MapEntityFromReader(reader);
            }

            return default;
        }

        public async Task<IEnumerable<T>> GetAsync(
            string? whereClause = null, 
            object? queryParams = null, 
            string? orderBy = null)
        {
            var results = new List<T>();

            var columnList = string.Join(", ", _metadata.Properties.Select(p => p.ColumnName));
            var sql = $"SELECT {columnList} FROM {_metadata.TableName}";

            if (!string.IsNullOrWhiteSpace(whereClause))
            {
                sql += $" WHERE {whereClause}";
            }

            if (!string.IsNullOrWhiteSpace(orderBy))
            {
                sql += $" ORDER BY {orderBy}";
            }

            await using var connection = await _dbService.GetNewOpenConnectionAsync();
            await using var command = new NpgsqlCommand(sql, connection);

            if (queryParams != null)
            {
                var properties = queryParams.GetType().GetProperties();
                foreach (var prop in properties)
                {
                    var value = prop.GetValue(queryParams);
                    command.Parameters.AddWithValue($"@{prop.Name}", value ?? DBNull.Value);
                }
            }

            await using var reader = await command.ExecuteReaderAsync();

            while (await reader.ReadAsync())
            {
                results.Add(MapEntityFromReader(reader));
            }

            return results;
        }
    }
}
